apiVersion: v1
kind: Service
metadata:
  name: openbao-node-port
  namespace: openbao
spec:
  type: NodePort
  selector:
    openbao-active: "true"
  ports:
    - port: 8200
      targetPort: 8200
      nodePort: 30200
