apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: openbao-secret-store
  namespace: lab
spec:
  provider:
    vault:
      # run `echo $BAO_ADDR` to get the server address 
      server: "<server-addr>"
      # path to the KV secrets engine
      path: "kv"
      # version of the KV secrets engine
      version: "v2"
      auth:
        kubernetes:
          # path of the Kubernetes auth method
          mountPath: "kubernetes"
          # role to use for the Kubernetes auth method
          role: "lab"
          serviceAccountRef:
            # service account to use for authentication
            name: "my-app"
